#!/usr/bin/env php
<?php
// +----------------------------------------------------------------------
// | ThinkPHP [ WE CAN DO IT JUST THINK ]
// +----------------------------------------------------------------------
// | Copyright (c) 2006-2018 http://thinkphp.cn All rights reserved.
// +----------------------------------------------------------------------
// | Licensed ( http://www.apache.org/licenses/LICENSE-2.0 )
// +----------------------------------------------------------------------
// | Author: yunwuxin <448901948@qq.com>
// +----------------------------------------------------------------------

namespace think;

// 加载基础文件
require __DIR__ . '/thinkphp/base.php';

// 定义应用目录
define('DS', DIRECTORY_SEPARATOR);

define('ROOT_PATH', dirname(__FILE__) . DS);

define('WOO_PATH', dirname(__FILE__) . DS . 'woo' . DS);
\think\Loader::addNamespace('woo', WOO_PATH);

define('APP_PATH', dirname(__FILE__) . DS . 'app' . DS);

define('WWW_ROOT', dirname(__FILE__) . DS . 'public' . DS);

define('ADDONS_PATH', ROOT_PATH . 'addons' . DS);




// 应用初始化
Container::get('app')->path(__DIR__ . '/app/')->initialize();



// 控制台初始化
Console::init();